### ISSUE TITLE
Feature Request: External Theme Support

### ISSUE THREAD

**Issue by markfaine** [gpakosz/.tmux#562] opened 2022-04-15 16:32 UTC
Such as those provided here https://github.com/jimeh/tmux-themepack, currently using both causes conflicts.

**Comment by gpakosz** [comment] 2022-07-14 16:02
Hello @markfaine 👋

Oh my tmux! comes with TPM integration. From what I saw when visiting https://github.com/jimeh/tmux-themepack, this can be used as a TPM plugin.

If you edit your `~/.tmux.conf.local` copy,
You can do
```
set -g @plugin 'jimeh/tmux-themepack'
set -g @themepack 'powerline/block/blue'
```
That being said, this tmux plugin takes the entire control of tmux `status-left` and `status-right` which may conflict with some of Oh my tmux! features.

Please give it a try and report your findings

**Comment by markfaine** [comment] 2022-10-01 16:09
> Hello @markfaine 👋
> 
> Oh my tmux! comes with TPM integration. From what I saw when visiting https://github.com/jimeh/tmux-themepack, this can be used as a TPM plugin.
> 
> If you edit your `~/.tmux.conf.local` copy, you can do
> 
> ```
> set -g @plugin 'jimeh/tmux-themepack'
> set -g @themepack 'powerline/block/blue'
> ```
> 
> That being said, this tmux plugin takes the entire control of tmux `status-left` and `status-right` which may conflict with some of Oh my tmux! features.
> 
> Please give it a try and report your findings

This is how I was using it, as a tpm plugin, however, it was breaking some functionality in oh-my-tmux, so I have since disabled it.  I guess it makes sense that they might not play nice together.  I was occasionally able to get some of the themes to work with oh-my-tmux and in some cases it produced great results but it was always fragile and sometimes there would be surprise glitches. It would be nice if they could work well together, though I understand that is probably a large undertaking.  If the theme that oh-my-tmux uses was a tpm plugin itself  that might present a way to make oh-my-tmux more customizable.  I know it's a lot easier said than done but it's just a suggestion.  The themes aspect of oh-my-tmux isn't really the main selling point for me. it's the other features and the bindings.  I see it as  a way to get tmux up and usable quickly without a lot of googling how to do x in tmux.

**Comment by gpakosz** [comment] 2022-12-28 18:05
Hello @markfaine 👋

You may want to try the `gh-536` branch

**Comment by gpakosz** [comment] 2022-12-28 18:09
Hello @markfaine 👋

You may want to try the `gh-536` branch.

That being said, if a plugin overwrites `status-left` and/or `status-right` entirely, then you will likely lose some of Oh my tmux! features.

**Comment by gpakosz** [comment] 2022-12-28 18:10
Dupe of #536

**Closed** 2023-01-03 21:12 UTC
Labels: duplicate, enhancement
