### ISSUE TITLE
“run '~/.tmux/plugins/tpm/tpm'” has no effect in .tmux.conf.local

### ISSUE THREAD

**Issue by tripleCC** [gpakosz/.tmux#61] opened 2017-03-27 03:23 UTC
```
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
#
# # Other examples:
# # set -g @plugin 'github_username/plugin_name'
# # set -g @plugin 'git@github.com/user/plugin'
# # set -g @plugin 'git@bitbucket.com/user/plugin'
#
# # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```
This was the code I added to .tmux.conf.local at the bottom. But it seems that tpm could't run as I expected.

When I added the code to .tmux.conf and  reloaded the configuration，the error below was throwed：

```
'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 127
```

But the strange thing was that I could use plugin of tmux normally this time. Spliting new pane would also throw the error.

How could I fix the error ? Any suggestion would be appreciated.

**Comment by gpakosz** [comment] 2017-04-02 12:13
Hello @tripleCC, I'm not a TPM user myself.

```
'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 127
```

This error usually means the `tmux` executable is not found in the path. You may want to see the output of
```
$ tmux run 'echo $PATH'
```

However, as far as I can tell, there's no straightforward way to make my configuration compatible with TPM:
  - I'm not familiar with TPM implementation
  - This would likely require changes on both sides
  - Using both kind-of defeats the purpose of having an easily transportable tmux configuration anyways

**Comment by vpassapera** [comment] 2017-04-24 01:59
TPM works fine for me. But you have to add it to .tmux.conf instead of the .local one.

**Comment by vpassapera** [comment] 2017-04-25 08:41
So, this is what I have in my ansible config and it seems to work.

```
    - name: Append to tmux configuration [.conf] (Plugins, etc)
      lineinfile:
        path: "/home/vpassapera/.tmux.conf"
        insertbefore: '# EOF'
        line: "{{ item }}"
      with_items:
        - set -g @plugin 'tmux-plugins/tpm'
        - set -g @plugin 'tmux-plugins/tmux-yank'
        - run '~/.tmux/plugins/tpm/tpm'
```

Have to do it on the .conf one. Before the line "#EOF" (This part is important).

**Comment by kuba-gaj** [comment] 2017-05-26 10:07
@tripleCC 
You need to use alternative plugin syntax if you want to have it in your .tmux.conf.local

See here: https://github.com/tmux-plugins/tpm/blob/master/docs/tpm_not_working.md

**Comment by well1791** [comment] 2017-06-16 01:42
Hi @gpakosz 👋 

I was facing this same problem too, but I managed to make it work through [this change](https://github.com/well1791/tpm/commit/3f3837ba6430c359ad243bef50f964f85a5033f1) in `tpm`.

Also, I was about to open the PR but, in order to justify a good reason for that change, I started to search for documentation related to `tmux.conf.local`, and I found nothing official (except for this awesome repository 👍).

So now my question is, where does this (elegant) approach of `.local` files come from? I suspect is some kind of Linux users good practice, and if that's the case I would lovely open a PR to `tpm` based on that good practice.

Best regards!

**Comment by gpakosz** [comment] 2017-06-16 05:52
Hello @well1791.

I don't plan myself to also take care of `tpm`. But would I open a PR, I would improve their [`_sourced_files()`](https://github.com/tmux-plugins/tpm/blob/c8ac32a085d382c43190bda4fb5972e531f501fd/scripts/helpers/plugin_functions.sh#L29-L32) function to support the these 3 possible situations:
  - `source foo`
  - `source -q foo` (tmux >= 2.3)
  - `if '[ -f foo ]' 'source foo'`

The third case is a bit more complicated because you would have to evaluate the condition before deciding the file will be sourced by tmux for real.

In the meantime, you can also decide to alter this configuration to replace
```
if '[ -f ~/.tmux.conf.local ]' 'source ~/.tmux.conf.local'
```
by
```
source ~/.tmux.conf.local
```
And try to add `set -g @plugin ...` lines to your `~/.tmux.conf.local` copy.

About a `.local` file, I don't believe it's an established pattern.

**Comment by luisliuchao** [comment] 2018-04-30 07:02
check this out https://github.com/tmux-plugins/tpm/issues/82

**Comment by bruno-** [comment] 2018-11-17 13:29
Hi guys,

if you're using `tmux.conf.local` and you have problems making `tpm` work there's an alternate plugin definition syntax described here (second issue from the top): https://github.com/tmux-plugins/tpm/blob/master/docs/tpm_not_working.md

```
# List of plugins
 set -g @tpm_plugins '          \
   tmux-plugins/tpm             \
   tmux-plugins/tmux-sensible   \
   tmux-plugins/tmux-resurrect  \
 '

 # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
 run '~/.tmux/plugins/tpm/tpm'
```

This approach is guaranteed to work with any tmux `source` command combination. No need to add support for `if '[ -f foo ]' 'source foo'` to `tpm`.

**Comment by luisdavim** [comment] 2019-01-08 13:53
#216 should fix this

**Comment by dcrasto** [comment] 2019-02-18 04:41
@bruno-  *bump*

**Comment by gpakosz** [comment] 2020-10-10 16:58
💁‍♂️ There is now a `tpm` branch up for testing that integrates Oh My Tmux! with TPM, see `.tmux.conf.local` for instructions

**Comment by vpassapera** [comment] 2020-10-15 06:13
I've been using the mainline branch with tpm for a long time. However, it is in `.tmux.conf` not local.

**Comment by gpakosz** [comment] 2020-10-15 06:38
Hello @vpassapera 👋

Please try the `tpm` branch and follow the instructions in the sample `.tmux.conf.local` file. There's no need to alter `.tmux.conf` file anymore.

**Comment by gpakosz** [comment] 2020-10-16 16:53
@luisdavim @tripleCC @well1791 did you get a chance to test the `tpm` branch?

**Comment by behaghel** [comment] 2020-10-31 12:37
@gpakosz I did but just using the provided `.tmux.conf.local` and uncommenting a couple of plugin instructions given as example doesn't do it. `<prefix> I` doesn't seem to be bound. I am not sure how to install these plugins. Thoughts? 

Otherwise, anything you'd like to be tested in particular?

**Comment by gpakosz** [comment] 2020-10-31 13:38
Hey @behaghel 👋

Here's the way to test the `tpm` branch
- make a backup of your current `~/.tmux.conf.local` file and your `~/.tmux` folder if needed
- `$ cd `
- `$ rm -rf .tmux`
- `$ git clone https://github.conf/gpakosz/.tmux --branch tpm`
- `$ ln -sf ~/.tmux/.tmux.conf` 
- `$ cp ~/.tmux/.tmux.conf.local .`
- then proceed to edit your `~/.tmux.conf.local` copy and follow the instructions at the end to enable tpm and plugins
- launch tmux

⚠️ Make sure you don't alter `.tmux.conf`. The sole fact of having `set -g @plugin ...` directives in your `~/.tmux.conf.local` copy should trigger automatic tpm and plugins installation.

**Comment by pquodling** [comment] 2020-11-01 09:22
shouldn't the git line be github.com not github.conf

**Comment by gpakosz** [comment] 2020-11-01 09:24
@pquodling thanks fixed the typo

**Comment by behaghel** [comment] 2020-11-01 18:55
I think I have followed the procedure faithfully but I am not getting much luck. The only thing that is changed is that `~/.tmux.conf.local` doesn't load automatically anymore. Once I do load it manually (<prefix> : source ~/.tmux.conf.local) it seems to ignore `set -g @plugin ...` instructions. I tested with the _resurrect_ plugin and I couldn't tell it had been installed and loaded. E.g. nothing in keybindings (<prefix> ?). I am on a debian buster with tmux in version 2.8-3.

**Comment by gpakosz** [comment] 2020-11-01 19:24
Hey @behaghel 👋

You're not supposed to source `~/.tmux.conf.local`.

I confirmed it didn't work with tmux `2.8`. Apparently in
```
source -q "~/.tmux.conf.local"
```
`~` is not expanded while it is when I don't use double quotes.

I pushed a fix. Sorry for that!

**Comment by behaghel** [comment] 2020-11-01 19:49
Hey @gpakosz, 

I pulled your fix and tried again …and it works! 👌 

Thanks for your great work.

**Comment by gpakosz** [comment] 2020-11-14 09:27
So?!

How is the testing going so far?

**Comment by behaghel** [comment] 2020-11-14 11:19
It just works. Have used that branch for the past 10 days and nothing to
report.

**Comment by gpakosz** [comment] 2020-11-14 12:24
Cool. "It just works" is indeed the goal

**Comment by gpakosz** [comment] 2020-12-21 18:53
If you're all happy I'll merge this next week

**Comment by CoryG89** [comment] 2020-12-28 04:31
I have also been using this for a while without any problems. +1

**Closed** 2021-01-09 20:06 UTC
Labels: branch available, enhancement, waiting for feedback

**Comment by sandikata** [comment] 2022-08-30 08:07
Installed plugins doesn't show up in status bar.

Example tmux-cpu.
