### ISSUE TITLE
tmux makes system unresponsive when restoring 

### ISSUE THREAD

**Issue by samarth-nagar** [gpakosz/.tmux#705] opened 2024-01-10 07:13 UTC
it freezes the entire system for 30 secons this didnt happened in start but it does now and every single time any way i can fix this

**Comment by gpakosz** [comment] 2024-01-10 09:58
Hello @samarth-nagar,

- What do you mean by "when restoring"?
- What OS are you using?
- Which tmux version?
- Did you enable TPM plugins?

**Comment by samarth-nagar** [comment] 2024-01-26 19:37
i apologise for poor issue information
* im using fedora 39 but same issue was in fedora 38 
* i have tmux next-3.4
* yes i did enabe tpm plugins 
* by restoring i mean when i open tmux after starting my pc the tmux reload from ressurect plugin which results inbetween of 10-30 seconds 

now that i think about it i should have addressed it to the ressurect plugin directly
 
i can give you my config if you want to recreate the same issue

**Comment by gpakosz** [comment] 2024-01-26 20:33
>  tmux reload from ressurect plugin which results in between of 10-30 seconds
If `tmux-resurrect` having issues I can't do much 🤷‍♂️

You may want to try the `gh-713` branch that adds instrumentation of TPM activity

**Comment by gpakosz** [comment] 2024-01-31 13:30
The `gh-713` branch has been merged.

Feel free to reopen this issue if you believe it's not solely caused by the `tmux-resurrect` plugin

**Closed by gpakosz** 2024-01-31 13:30 UTC
Labels: waiting for feedback, tpm
