### ISSUE TITLE
Add CPU util, load mem stats

### ISSUE THREAD

**Issue by agiuliano** [gpakosz/.tmux#173] opened 2018-07-21 15:26 UTC
It would be awesome to have by default resources stats from https://github.com/samoshkin/tmux-plugin-sysstat

**Comment by kleinjm** [comment] 2018-11-29 19:03
@agiuliano did you get tmux-plugin-sysstat working with oh-my-tmux using `tmux_conf_theme_status_right` or `_left`?

**Comment by Glitches** [comment] 2019-03-01 18:25
Is it possible to use sysstat?? 
I was trying today and couldn't get it to work...

**Comment by danielporto** [comment] 2019-04-11 15:24
That would be great!!

**Comment by gpakosz** [comment] 2020-11-12 12:14
Closing as duplicate of #61

**Closed by gpakosz** 2020-11-12 12:14 UTC
Labels: duplicate, new feature
