### ISSUE TITLE
Breaking Powerlevel 10K fonts, colors and text on zsh

### ISSUE THREAD

**Issue by rapidclock** [gpakosz/.tmux#577] opened 2022-07-03 00:01 UTC
I am on an M1 Mac with zsh and using Powerlevel 10K plugin via oh-my-zsh.
I am using `MesloLGS NF` font (the one recommended by P10k folks).
I am also using iTerm2.

I have a couple of zsh plugins like zsh-syntax-highlighting and zsh-auto-completions.

I have used the above combinations before and never had a problem with `gpakosz/.tmux`.
I wonder if it is something in the recent commits that caused this regression.

Whenever I activate tmux, the colors and fonts on my terminal are broken. I have a small video demo showing what I am talking about.

https://user-images.githubusercontent.com/19704351/177019365-541da788-3663-4b3a-b1af-878154bda33d.mp4

**Comment by gpakosz** [comment] 2022-07-08 21:14
Hello @rapidclock 👋

Sounds like a dupe of #575

**Comment by babaolanqiu** [comment] 2022-07-20 03:38
> Hello @rapidclock 👋
> 
> Looks like a dupe of #575

Same issue here, and this didn't solve my problem.

**Comment by gpakosz** [comment] 2022-07-20 04:51
Sorry I meant #530 

Can you try adding `set -g default-terminal "screen-256color"` to your `~/.tmux.conf.local` copy?

**Comment by babaolanqiu** [comment] 2022-07-20 06:27
This works fine. Thanks!

**Comment by gpakosz** [comment] 2022-07-20 08:29
> This works fine. Thanks!

This means that your macOS has a broken definition of `tmux-256color` terminal description though

**Closed** 2022-12-28 21:39 UTC
Labels: tmux support, external

**Comment by h4rvey-g** [comment] 2023-07-21 08:48
@gpakosz Hi, this happened again after I recently updated .tmux. Could you please take a look? I have set `set -g default-terminal "screen-256color"`

https://github.com/gpakosz/.tmux/assets/32609824/da65faea-f743-4967-b450-8aea9d5d67d8

**Comment by gpakosz** [comment] 2023-07-21 09:45
Hello @h4rvey-g 

You likely now need to use `#!important` in your `.local` customization file
```
set -g default-terminal "screen-256color" #!important
```

**Comment by h4rvey-g** [comment] 2023-07-21 12:42
It's solved! Thanks!
