### ISSUE TITLE
Very slow on msys2, and powerline is not rendered  correctly.

### ISSUE THREAD

**Issue by eromoe** [gpakosz/.tmux#95] opened 2017-07-06 06:03 UTC
Hi, I am using msys2

I see the attention for cygwin:
> I don't recommend running this configuration with Cygwin anymore. Forking under Cygwin is extremely slow and this configuration issues a lot of run-shell commands under the hood

Is slow on msys2 by this too? If so, Any plan to provide  a  minimum version ?

------

For powerline:

font is correct:
![image](https://user-images.githubusercontent.com/3938751/27897373-8081840e-6252-11e7-8055-9fd5a7d771dd.png)

And vim is fine:
![image](https://user-images.githubusercontent.com/3938751/27897354-65a4329e-6252-11e7-85c9-1be9177177e4.png)

But tmux not:
![image](https://user-images.githubusercontent.com/3938751/27897345-5aa83f70-6252-11e7-9df0-fc5c1fea9fa8.png)

I can't figure this out..

**Comment by gpakosz** [comment] 2017-07-06 06:34
Hello @eromoe, [as noted in README](https://github.com/gpakosz/.tmux#using-the-configuration-under-cygwin-within-mintty), `fork()` under Cygwin / MSYS2 is extremely slow and there's pretty much nothing I can do about it.

To trim down the configuration, edit your `~/.tmux.conf.local` copy and edit `tmux_conf_theme_status_left` and `tmux_conf_theme_status_right` variables. Stop using battery indicator, uptime, username, hostname...

As for Powerline symbols, did you edit your `~/.tmux.conf.local` copy to enable them?

**Comment by gpakosz** [comment] 2017-07-06 06:35
Somewhat a dupe of #50

**Comment by eromoe** [comment] 2017-07-06 07:00
Is this right ? But still slow...
```
tmux_conf_theme_status_left=' ❐ #S | '
tmux_conf_theme_status_right='#{prefix}#{pairing} '
```
-----

At first I think tmux would auto show the powerline font,  because vim looks good and no need config after `vim-airline` and `vim-airline-themes` installed, so I am not know that powerline is need to be config... sorry

now I enable the 
```
tmux_conf_theme_left_separator_main=''  # /!\ you don't need to install Powerline
tmux_conf_theme_left_separator_sub=''   #   you only need fonts patched with
tmux_conf_theme_right_separator_main='' #   Powerline symbols or the standalone
tmux_conf_theme_right_separator_sub=''  #   PowerlineSymbols.otf font
```
Angle does show, but not so pretty as in vim...
![image](https://user-images.githubusercontent.com/3938751/27898941-d2928772-625a-11e7-8dff-8a99e03c05a1.png)

Is that mean I need find proper char( like '' ) in my font , and assign to variables  `tmux_conf_theme_left_separator_main` etc. ?

**Comment by gpakosz** [comment] 2017-07-06 07:06
> Is this right ? But still slow...
> ```
> tmux_conf_theme_status_left=' ❐ #S | '
> tmux_conf_theme_status_right='#{prefix}#{pairing} '
> ```

Did you reload the configuration? Try doing so by typing `<prefix> + r`. Once configuration is reloaded can you paste the output of
```
$ tmux show -g status-left
$ tmux show -g status right
```

>Angle does show, but not so pretty as in vim...

True, this is because MinTTY has a GDI based renderer.

**Comment by eromoe** [comment] 2017-07-06 07:36
I have reloaded the config.  
output:
```
$ tmux show -g status-left
status-left "#[fg=#000000,bg=#ffff00,bold] ❐ #S #[fg=#ffff00,bg=#ff00af,none]#[fg=#e4e4e4,bg=#ff00af,none] #[fg=#ff00af,bg=default,none] "

$ tmux show -g status right
usage: show-options [-gqsvw] [-t target-session|target-window] [option]
```

PS: On my test, it looks like, keep enter  and quit `tmux` would make `ssh-agent.exe` cost 25% cpu and in some time would get stuck. But I also confirm tmux is still slow  after mysy2 refresh restart.

**Comment by gpakosz** [comment] 2017-07-06 07:50
Typo on my part, it's `$ tmux show -g status-right`

**Comment by eromoe** [comment] 2017-07-06 08:08
Oh, I don't look carefully too, sorry . This is the output
```
$ tmux show -g status-right
status-right "#[fg=#080808,bg=default,none]#[fg=#8a8a8a,bg=#080808,none]#[fg=none]#[bg=none]#[none]#{?client_prefix,⌨,}#[fg=none]#[bg=none]#[none]#{?session_many_attached,👓,} "
```

**Comment by gpakosz** [comment] 2017-07-06 08:35
Right, in both output you pasted there are no more `#(cut -c3- ~/.tmux.conf | sh -s XXX)` calls, where `XXX` denotes parameters. This means the overhead comes from Cygwin / MSYS2 only and there's pretty much nothing you can do about it.

**Closed** 2020-09-06 15:29 UTC
Labels: external
