### ISSUE TITLE
Can i use TPM with this config?

### ISSUE THREAD

**Issue by fwarmuth** [gpakosz/.tmux#276] opened 2019-08-20 21:59 UTC
hey, first THANKS for the great config.

Issue:
I am looking for a way to use some tmux plug ins, I would love to mange them via TPM.
What is the best practice while using this config?
especially looking for a way to use https://github.com/tmux-plugins/tmux-resurrect

regards

**Comment by gpakosz** [comment] 2019-08-21 20:27
Hello @fwarmuth 👋

I'm not a TPM user myself but as far as I remember people got it working with TPM. Search the issues queue.

I'll think about adding instructions but as I don't use TPM myself, I don't want this configuration make people believe I'm the good person to answer TPM related questions.

**Comment by ZaydH** [comment] 2019-09-10 09:56
One issue that discusses `tpm` and oh-my-tmux is #228.  I followed that approach and it works.  

I am *very* new to `tpm`.  I had assumed it would just work with oh-my-tmux, but eventually figured out it didn't and found this issue  I agree that something in the README may be useful to others.

**Comment by mdigga39** [comment] 2020-04-17 20:11
Sourced from an issue on TPM page: 

> TPM has a known issue when using a custom config file with the `-f` option. The solution is to use alternative plugin definition syntax. Here are the steps to make it work:
> 
> remove all `set -g @plugin` lines from tmux config file
> 
> in the config file define the plugins in the following way:
> 
> ```
>  # List of plugins
>  set -g @tpm_plugins '          \
>    tmux-plugins/tpm             \
>    tmux-plugins/tmux-sensible   \
>    tmux-plugins/tmux-resurrect  \
>  '
> 
>  # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
>  run '~/.tmux/plugins/tpm/tpm'
>```
> Reload TMUX environment so TPM is sourced: $ tmux source /path/to/my_tmux.conf
> 
> The plugins should now be working.

**Comment by gpakosz** [comment] 2020-10-10 16:58
💁‍♂️ There is now a `tpm` branch up for testing that integrates Oh My Tmux! with TPM, see `.tmux.conf.local` for instructions

**Comment by gpakosz** [comment] 2020-11-12 12:15
Closing as duplicate of #61

**Closed by gpakosz** 2020-11-12 12:15 UTC
Labels: duplicate, enhancement
