### ISSUE TITLE
How to source file in tmux.conf.local

### ISSUE THREAD

**Issue by owenstake** [gpakosz/.tmux#702] opened 2024-01-05 03:46 UTC
I want to source extra config file in tmux.conf.local .
I have try add the following line at the end of tmux.conf.local, but it failed.
```bash
source ~/xx/xx/tmux.conf
```
How to achieve this goal?

**Comment by gpakosz** [comment] 2024-01-05 06:52
Hello @owenstake,

Place line in this section of your `.local` customization file
```
# -- user customizations -------------------------------------------------------
```

**Comment by owenstake** [comment] 2024-01-05 08:00
> Hello @owenstake,
> 
> Place line in this section of your `.local` customization file
> 
> ```
> # -- user customizations -------------------------------------------------------
> ```

It not works. I always add this source line at the end of .tmux.conf.local . The sourced file has a lot of configuration about shortcut and plugin.

**Comment by owenstake** [comment] 2024-01-05 08:16
> > Hello @owenstake,
> > Place line in this section of your `.local` customization file
> > ```
> > # -- user customizations -------------------------------------------------------
> > ```
> 
> It not works. I always add this source line at the end of .tmux.conf.local . The sourced file has a lot of configuration about shortcut and plugin.
plugin is not take effective in my soured file.
```bash
    set -g @plugin 'tmux-plugins/tmux-sensible'
    set -g @plugin 'tmux-plugins/tmux-resurrect'     # save session
```

**Comment by gpakosz** [comment] 2024-01-05 10:48
Specifying plugins for anywhere else than the `.local` customization file itself is not supported

**Comment by gpakosz** [comment] 2024-01-30 14:16
Duplicate of #671

**Closed by gpakosz** 2024-01-30 14:16 UTC
Labels: duplicate
