### ISSUE TITLE
tmux.conf instead of .tmux.conf "ln -s -f /path/to/oh-my-tmux/.tmux.conf ~/.tmux.conf"?

### ISSUE THREAD

**Issue by sisrfeng** [gpakosz/.tmux#414] opened 2020-10-02 11:20 UTC
/path/to/oh-my-tmux/.tmux.conf can not be found

**Comment by gpakosz** [comment] 2020-10-02 12:09
Hello @sisrfeng 👋

`/path/to/oh-my-tmux/.tmux.conf` is just an example.

I suggest you stick to the default install method
```
$ cd
$ git clone https://github.com/gpakosz/.tmux.git
$ ln -s -f .tmux/.tmux.conf
$ cp .tmux/.tmux.conf.local .
```

**Comment by sisrfeng** [comment] 2020-10-02 12:26
Thx!
Should we do this first:
![image](https://user-images.githubusercontent.com/53520949/94922684-3e111800-04ed-11eb-9464-8a3244fdae93.png)
then this? :
$ cd
$ git clone https://github.com/gpakosz/.tmux.git
$ ln -s -f .tmux/.tmux.conf
$ cp .tmux/.tmux.conf.local .

What's more, I modify  .tmux/.tmux.conf.local  and nothing change. Then I modify   .tmux/.tmux.conf, things go in the way I want.
What is the relationship between these two files?

**Comment by gpakosz** [comment] 2020-10-10 17:03
Hey @sisrfeng 👋

💁‍♂️ There is now a `tpm` branch up for testing that integrates Oh My Tmux! with TPM, see `.tmux.conf.local` for instructions

**Comment by gpakosz** [comment] 2020-11-12 12:45
Closing as duplicate of #61

**Closed** 2020-11-12 12:58 UTC
Labels: duplicate, enhancement
