### ISSUE TITLE
bindings defined in .tmux.conf.local cannot override ones defined in .tmux.conf

### ISSUE THREAD

**Issue by kflu** [gpakosz/.tmux#571] opened 2022-05-27 17:26 UTC
`Escape` in copy-vi-mode is bound to `send-keys -X cancel`. I want to change it to `clear-selection` in .tmux.conf.local. However, it doesn't take effect

## Repro
Put below in `.tmux.conf.local`:

```
bind-key -T copy-mode-vi Escape     send-keys -X clear-selection
```

Now completely quit and restart tmux. Then do:

```sh
tmux list-keys | grep copy-mode-vi | grep Es
```

## Actual Result

Escape is still bound to cancel

```
bind-key    -T copy-mode-vi Escape               send-keys -X cancel
```

## Expected

I expect Escape should now bound to clear-selection.

**Comment by kflu** [comment] 2022-05-27 17:39
It looks like I'll have to wrap it with `run -b 'tmux bind ...` in order for it to work:

```
# works
run -b 'tmux bind-key -T copy-mode-vi Escape     send-keys -X clear-selection 2> /dev/null || true'
```

Note that, for a binding NOT defined in `.tmux.conf`, I can define them WITHOUT the wrap:

```
# works, because `copy-mode-vi q` is not defined in .tmux.conf
bind-key -T copy-mode-vi q     send-keys -X cancel
```

**Comment by yhshin11** [comment] 2022-06-08 06:35
I'm having the same issue and found it extremely frustrating. It seems like others are experiencing the same thing, as seen in #549.

I think this might be because of something that changed on tmux's end, because I remember this working properly before. For reference, I have tmux 3.0a on my system.

What I found to work is to edit `.tmux.conf` so that `source -q ~/.tmux.conf.local` happens **after** `run 'cut -c3- ~/.tmux.conf | sh -s _apply_configuration'`.

So you would edit [this part](https://github.com/gpakosz/.tmux/blob/master/.tmux.conf#L168) like so:
```
# -- 8< ------------------------------------------------------------------------

run 'cut -c3- ~/.tmux.conf | sh -s _apply_configuration'

# -- user defined overrides ----------------------------------------------------

source -q ~/.tmux.conf.local
```


@gpakosz Could you comment on if this is a valid fix, or if it's idiotic in ways that I'm not aware of?

**Comment by gpakosz** [comment] 2022-06-08 17:46
Hello there 👋

Can you please give the `gh-571` a try?
- It's rebased on `gh-514` which means you can control whether or not tmux alters `new-window`, `split-window` and `new-session` bindings
- It should apply all `bind` / `unbind` commands found in `~/.tmux.conf.local` last

**Comment by yhshin11** [comment] 2022-06-09 02:25
Confirming that `gh-571` worked for me. Thanks!

**Comment by gpakosz** [comment] 2022-06-11 20:04
I realized `gh-514` is likely not needed so I force pushed `gh-571` with a single commit on top of `master`.

Can you please give it another try?

**Comment by yhshin11** [comment] 2022-06-15 01:51
@gpakosz I can confirm that this is working in `master`. Cheers!

**Comment by gpakosz** [comment] 2022-07-14 15:42
Hello again,

I changed the `gh-571` branch again. Can you please give it a try?

There are 2 distinct needs that need to be addressed by Oh my tmux!

1. People wanting to change a binding, yet still benefiting form Oh my tmux! binding manipulation.
    This is the case when you e.g. want `<prefix> w` to create a new window instead of `<prefix> c`.
    ```
    unbind c
    bind w new-window
    ```
    And at the same time you want to leverage `tmux_conf_new_window_retain_current_path=true` so that `bind w new-window` automatically becomes `bind w new-window -c #{pane_current_path}`

2. People wanting to add additional bindings that are immune to Oh my tmux! manipulations. This is your need, and in such a case you now need to terminate your binding definition with `#!important` (inspired by CSS).
    ```
    bind-key -T copy-mode-vi Escape send-keys -X clear-selection #!important
    ```
    This mechanism works for any tmux command.

**Comment by gpakosz** [comment] 2022-07-16 19:13
@kflu @yhshin11 

I updated `.tmux.conf` the sample `.tmux.conf.local` in the `gh-571` branch. I'm testing it a bit more and I'll merge it soon

**Closed** 2022-07-21 19:00 UTC
Labels: enhancement, branch available
