### ISSUE TITLE
How to know what is being processed while starting tmux? 

### ISSUE THREAD

**Issue by programus** [gpakosz/.tmux#499] opened 2021-07-12 08:22 UTC
OS: macOS Big Sur 11.4
Shell: zsh (Oh My Zsh)
tmux: 3.2a (installed by `brew` )
terminal: kitty

----
I am using tmux with oh my tmux, everything works great until today. 

Today, after I restart my system, it suddenly became extremely slow while I starting tmux. Even more, it slows down the whole system. But I found the CPU is not used so much. 

In the status bar, it displays something like `cut -c3- ~/.tmux.conf | sh -s _username /dev/ttys001 false %0` with a `not ready` . 

Even it is started, no response in the panel. I cannot input any commands. 

I don't think this is a tmux problem or oh my tmux problem, this may because some of the initializing processes are slow. 

So I want to know whether there is a way to print out what it is doing while start tmux so I can find out what command slow the whole progress down. That may a big problem on this system.  

----
Some other things I have tried. 

* remove `.tmux` folder as well as `.tmux.conf` and `.tmux.conf.local` and restart tmux, not slow and works good. 
* re-clone `.tmux` again and use the default `.tmux.conf.local` , slow again. 
* reinstall `tmux` by `brew reinstall tmux`, no luck.
* `brew upgrade` , not improved. 
* restart the system again, no help.

**Comment by gpakosz** [comment] 2021-07-12 09:45
Hello @programus 👋

I can't reproduce this. I freshly installed Big Sur, tmux, Oh My Zsh and Oh my tmux!

The only think I don't have is Kitty. Can you please try with `Terminal.app`?

Also, can you make sure you disable all plugins (TPM and Oh My Zsh)?

**Comment by programus** [comment] 2021-07-12 12:23
> Hello @programus 👋
> 
> I can't reproduce this. I freshly installed Big Sur, tmux, Oh My Zsh and Oh my tmux!
> 
> The only think I don't have is Kitty. Can you please try with `Terminal.app`?
> 
> Also, can you make sure you disable all plugins (TPM and Oh My Zsh)?

@gpakosz Thank you for you response. I also guess you could not reproduce this. It also had worked very well for quite a long time on my PC. So I think this is only a problem on my PC. 

I guess there are some other problems that slowed one or some of the initializing commands in oh my tmux. So I hope you can  tell me how I can get the log or what it is busy in so I can find out what is the command became slow. 

I tried a lot after I post this and I found it works normally if I comment this: 

```
#   _apply_overrides
# #  _apply_theme&
#   _apply_bindings&
```

Also, if I comment this part, the speed also come back. (Of course I lost the feature I commented. )

```
#     status_right=$(echo "$tmux_conf_theme_status_right" | sed \
#       -e "s/#{pairing}/#[fg=$tmux_conf_theme_pairing_fg]#[bg=$tmux_conf_theme_pairing_bg]#[$tmux_conf_theme_pairing_attr]#{?session_many_attached,$tmux_conf_theme_pairing ,}/g" \
#       -e "s/#{prefix}/#[fg=$tmux_conf_theme_prefix_fg]#[bg=$tmux_conf_theme_prefix_bg]#[$tmux_conf_theme_prefix_attr]#{?client_prefix,$tmux_conf_theme_prefix ,$(printf "$tmux_conf_theme_prefix" | sed -e 's/./ /g') }/g" \
#       -e "s/#{mouse}/#[fg=$tmux_conf_theme_mouse_fg]#[bg=$tmux_conf_theme_mouse_bg]#[$tmux_conf_theme_mouse_attr]#{?mouse,$tmux_conf_theme_mouse ,$(printf "$tmux_conf_theme_mouse" | sed -e 's/./ /g') }/g" \
#       -e "s%#{synchronized}%#[fg=$tmux_conf_theme_synchronized_fg]#[bg=$tmux_conf_theme_synchronized_bg]#[$tmux_conf_theme_synchronized_attr]#{?pane_synchronized,$tmux_conf_theme_synchronized ,}%g" \
#       -e 's%#{circled_session_name}%#(cut -c3- ~/.tmux.conf | sh -s _circled #S)%g')
```

But I realized that it is not because the `sed` here, but just because some others may slow my PC down might be skipped because the status_right does not include some pattern that could trigger the process on. 

I cannot figure out what it is because the function is a little complex for me. 

So I hope you can help me solve this puzzle since I don't think it is possible for you to reproduce the problem on any PC but the one I am working on.

**Comment by programus** [comment] 2021-07-12 12:41
@gpakosz Actually, if it is only a long initialization time, it is not a big problem. What most trouble me is that even it finished the initialization, I cannot input in the panel. I have to wait many seconds after every key press to know what I just pressed. 

So if there is any process run on every key press event, I hope you can tell me since it may be one of the reasons.

**Comment by programus** [comment] 2021-07-12 12:47
@gpakosz Some new findings. 

If I only comment this as well as the definition of `tmux_conf_theme_status_right` in `.tmux.conf.local` : 
```
#   # tmux_conf_theme_status_right=${tmux_conf_theme_status_right-' #{prefix}#{mouse}#{pairing}#{synchronized}#{?battery_status, #{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} , %R , %d %b | #{username}#{root} | #{hostname} '}
```

it is also fixed. But if I only comment  as well as the definition of `tmux_conf_theme_status_left` in `.tmux.conf.local` 
```
#   # tmux_conf_theme_status_left=${tmux_conf_theme_status_left-' ❐ #S | ↑#{?uptime_y, #{uptime_y}y,}#{?uptime_d, #{uptime_d}d,}#{?uptime_h, #{uptime_h}h,}#{?uptime_m, #{uptime_m}m,} '}
```

The problem is still there. I think the reason may some part in the right status bar.

**Comment by programus** [comment] 2021-07-12 14:18
@gpakosz OK. After some try. I think I find out what makes it slow, but I still do not know why. 

After I removed `#{username}#{root} | #{hostname}` from `tmux_conf_theme_status_right` , it is fixed. 

I also tried to run the `cut -c3- ~/.tmux.conf | sh -s _username "" false` and `cut -c3- ~/.tmux.conf | sh -s _hostname` in my terminal, they both return immediately and both are not slow at all. 

I think I can live without these two in status bar. But I would be very glad to know the reason if you know it.

**Comment by gpakosz** [comment] 2021-07-12 14:19
What you can try is

- edit your `~/.tmux.conf.local` copy
- make sure TPM plugins are disabled (comment out all the `set -g plugin ...` lines)
- remove all variables from `tmux_conf_theme_status_right` and add them back until the problem appears again

I suspect the slowness comes from `#{username}`, `#{root}` or #{hostname}`

**Comment by programus** [comment] 2021-07-12 14:22
> What you can try is
> 
> * edit your `~/.tmux.conf.local` copy
> * make sure TPM plugins are disabled (comment out all the `set -g plugin ...` lines)
> * remove all variables from `tmux_conf_theme_status_right` and add them back until the problem appears again
> 
> I suspect the slowness comes from `#{username}`, `#{root}` or #{hostname}`

Yes, you are correct. `#{username}`, `#{root}` and #{hostname}` are the cause of the slowness. But why? And is it possible to fix them? I do not really always need them but sometime they are helpful, especially while I ssh to many servers at the same time...

**Comment by gpakosz** [comment] 2021-07-12 14:26
Is there any of the 3 that causes the slowness?

**Comment by programus** [comment] 2021-07-12 14:30
> Is there any of the 3 that causes the slowness?

I think all the 3 cause the slowness, because it back to the normal speed only when I remove all 3.

**Comment by gpakosz** [comment] 2021-07-12 14:31
> because it back to the normal speed only when I remove all 3

That's weird and I don't know what's going on really. If a single of the 3 causes the slowness then it's easier to debug

**Comment by programus** [comment] 2021-07-12 14:33
Is there anyway I can find out what is slow? I tried `cut -c3- ~/.tmux.conf | sh -s _username "" false` and `cut -c3- ~/.tmux.conf | sh -s _hostname` but none is slow.

**Comment by gpakosz** [comment] 2021-07-12 14:37
Can you please try the `gh-499` branch?

**Comment by programus** [comment] 2021-07-12 14:40
> Can you please try the `gh-499` branch with all the 3 variables enabled?

`gh-499` is the same, extremely slow. :-(

**Comment by gpakosz** [comment] 2021-07-12 14:46
Within tmux, please do
```
$ tmux display -p '#{pane_tty}'
```
This should give you back something like `/dev/ttysXXX`.

Then use that value to call
```
$ cut -c3- ~/.tmux.conf | sh -s _username /dev/ttysXXX false
```
Also please paste the output of 
```
$ ps -t /dev/ttysXXX -o user=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -o pid= -o ppid= -o command=
```

**Comment by programus** [comment] 2021-07-12 14:54
> Within tmux, please do
> 
> ```
> $ tmux display -p '#{pane_tty}'
> ```
> 
> This should give you back something like `/dev/ttysXXX`.
> 
> Then use that value to call
> 
> ```
> $ cut -c3- ~/.tmux.conf | sh -s _username /dev/ttysXXX false
> ```
> 
> Also please paste the output of
> 
> ```
> $ ps -t /dev/ttysXXX -o user=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -o pid= -o ppid= -o command=
> ```

OK. 

```bash
$ cut -c3- ~/.tmux.conf | sh -s _username /dev/ttys000 false
root 
```

and this command took more than 1 min to finish. 

Also here is the output of ps, this also took more than 1 min. 
```
$ ps -t /dev/ttys000 -o user=root -o pid= -o ppid= -o command=
root
<my-current-login-user>  6985  6671 -zsh
```

Sorry, I have to mask my current user since it is a company account.

**Comment by gpakosz** [comment] 2021-07-12 14:58
I'm a bit surprised by `/dev/ttys000`. I guess if you open other panes you'll get other values.

And I believe you found out the cause for the slowness: `ps`. 

Also please do not replace `-o user=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`. That's my fault, the `XXX` there are not a placeholder but a way to ask for a long enough column width.

So please try with
```
$ ps -t /dev/ttys000 -o user= -o pid= -o ppid= -o command=
```
Redact as much as you want but I need to know the number of lines the `ps` command outputs

**Comment by gpakosz** [comment] 2021-07-12 15:02
Also, what does `which ps` say? Here I have
```
$ which ps
/bin/ps
```

**Comment by programus** [comment] 2021-07-12 15:09
Sorry. I didn't realize the `XXXXXXXXXXXXX` is not a placeholder, even I wondered why this is so long... :-D

The output of `user=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX` is 

```bash
$ ps -t /dev/ttys000 -o user=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -o pid= -o ppid= -o command=
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX             
<my-login-user>              6985  6671 -zsh
root                            10914  6985 ps -t /dev/ttys000 -o user=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -o pid= 
```

And `which ps` is the same as yours. 

```bash
$ which ps
/bin/ps
```

Yes. I got different value of tty in other pane. But it also took more than 1 min to finish the `ps` command.
Even just `ps -t /dev/ttyXXXX` is slow. 

But why is `ps` slow?

**Comment by gpakosz** [comment] 2021-07-12 15:12
Are you using Docker?

**Comment by gpakosz** [comment] 2021-07-12 15:13
The slowness could come from lots of zombie process or high load

**Comment by programus** [comment] 2021-07-12 15:20
> Are you using Docker?

No. At least not now. I have docker desktop installed but not start it now. 

> The slowness could also come from lots of zombie process or high load

Maybe but it happens even after I just reboot my computer. 

Anyway, I believe this is not actually an oh my tmux issue from the start. I just hope you can give me some hints to solve it. Indeed, you helped me a lot! Thank you very much! 

If you know the reason or have any other ideas about why the `ps`, I would like to hear and try by myself. If you also just feel it is weird like me, I do not mind if you close this issue and help others. 

Again, thank you very much!! 
Not only for your help on this issue but also for this great configuration of tmux, which really saved tons of my time to config tmux.

**Comment by gpakosz** [comment] 2021-07-12 15:24
A thing to try
```
COLUMNS=10 ps -t /dev/ttys000
```
But I doubt `ps` taking time to estimate the terminal width could be the cause.

BTW is just typing `ps` without any option also slow?

**Comment by programus** [comment] 2021-07-12 15:27
> A thing to try
> 
> ```
> COLUMNS=10 ps -t /dev/ttys000
> ```
> 
> But I doubt `ps` taking time to estimate the terminal width could be the cause.
> 
> BTW is just typing `ps` without any option also slow?

Just `ps` is very fast. `ps -ef` is also very fast. But unfortunately, `COLUMNS=10 ps -t /dev/ttys000` is low, more than 1 min to return. :-(

**Comment by gpakosz** [comment] 2021-07-12 15:28
Is it slow for all values of `/dev/ttysXXX`?

**Comment by gpakosz** [comment] 2021-07-12 15:29
Are there many zombies? `$ ps aux | grep Z`

**Comment by programus** [comment] 2021-07-12 15:34
> Are there many zombies? $ ps aux | grep Z

Not so may zombies. The command returns 2 lines, one is the `grep Z` and the other is an extension of finder. 

```bash
$ ps aux | grep Z
USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
<my-login-user> 19844   0.9  0.0  4277624    676 s001  R+   12:31AM   0:00.01 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox Z
<my-login-user>   912   0.0  0.1  4400408  10164   ??  Ss    2:49PM   0:00.79 /Applications/BetterZip.app/Contents/PlugIns/FinderSyncExtension.appex/Contents/MacOS/FinderSyncExtension
_coreaudiod        260   0.0  0.0  4330848   1652   ??  Ss    2:47PM   0:00.12 Core Audio Driver (ZoomAudioDevice.driver)
```

> Is it slow for all values of /dev/ttysXXX?

Looks like YES. I tried `/dev/ttys001` `/dev/ttys002` `/dev/ttys000` `/dev/ttys0` `/dev/ttys1` . All slow.

**Comment by programus** [comment] 2021-07-12 15:39
> I'm a bit surprised by /dev/ttys000. 

About the `/dev/ttys000`. I tried finished tmux as well as kitty, the terminal app, and restart kitty and then tmux, it became `/dev/ttys001` and the `/dev/ttys000` is used by kitty this time. 

So the `/dev/ttys000` is because when I start tmux, kitty is using `/dev/ttys001` . Maybe because I tried `Terminal.app` once.

**Comment by gpakosz** [comment] 2021-07-12 15:41
Is `ps -t` slow outside of tmux as well?

**Comment by programus** [comment] 2021-07-12 15:42
> Is `ps -t` slow outside of tmux as well?

Yes.

**Comment by gpakosz** [comment] 2021-07-12 15:42
Even after a fresh reboot without starting tmux once?

**Comment by programus** [comment] 2021-07-12 15:51
> Even after a fresh reboot without starting tmux once?

I may try this tomorrow. :-) 

btw. I found this is fast and may also can get almost the same result as your current `ps` command options. 

```bash
$ ps -t /dev/ttys001 -o user=XXXXXXXXXXXXXXXXXXXXXX -o pid= -o ppid= -o command=
XXXXXXXXXXXXXXXXXXXXXX
<my-login-user>    23002 22678 -zsh
root                   26752 23002 ps -t /dev/ttys001 -o user=XXXXXXXXXXXXXXXXXXXXXX -o pid= -o ppid= -o command=


$ ps -o user= -o pid= -o ppid= -o command= -o tty=|grep ttys001|grep -v grep
<my-login-user> 23002 22678 -zsh             ttys001
```

I am not sure how to modify the `awk` script part,

**Comment by programus** [comment] 2021-07-12 17:19
@gpakosz I found that as long as the tty device is a parameter, it becomes slow. 

I tried to add a very simple function in `.tmux.conf` 

```bash
# EOF
#
# # exit the script if any statement returns a non-true return value
# set -e
#
# unset GREP_OPTIONS
# export LC_NUMERIC=C
#
# f() {
#   echo $1
# }
# 
```

And then 

```bash
$ cut -c3- ~/.tmux.conf | sh -s f /dev/ttys001
/dev/ttys001
```

This took about 1 minute. But the following commands returns immediately. 
```bash
$ cut -c3- ~/.tmux.conf | sh -s f ttys001
ttys001

$ cut -c3- ~/.tmux.conf | sh -s f /dev/ttys008. # there is no /dev/ttys008 on my device now
/dev/ttys008
```
I totally have no idea about this.

**Comment by gpakosz** [comment] 2021-07-12 19:32
Does the following also takes 1 min?

```
$ echo foo > /dev/ttysXXX
```

**Comment by programus** [comment] 2021-07-13 02:16
> Does the following also takes 1 min?
> 
> ```
> $ echo foo > /dev/ttysXXX
> ```

No, this returns immediately. 
```bash
$ date && echo foo > /dev/ttys013 && date
Tue Jul 13 11:15:34 JST 2021
foo
Tue Jul 13 11:15:34 JST 2021
```

I am completely confused...

**Comment by gpakosz** [comment] 2021-07-13 05:36
> Well, I think I may be able to remove all /dev/ from the $tty in the .tmux.conf as a walk-around.

Well it's done already in `_tty_info()`

Did you try removing Oh My Zsh?

**Comment by programus** [comment] 2021-07-13 05:48
> > Well, I think I may be able to remove all /dev/ from the $tty in the .tmux.conf as a walk-around.
> 
> Well it's done already in `_tty_info()`

I am afraid it is not done yet. Because the `$1` in `_tty_info()` is `/dev/ttysXXX` , passing this parameter would slow down the whole progress. So the removing `/dev/` logic must be put into where the `$tty` is created. 

> Did you try removing Oh My Zsh?

No. But I tried to set default shell to `bash`, but nothing changed. So I suppose it is not because Oh My Zsh.

**Comment by gpakosz** [comment] 2021-07-13 06:00
> Because the `$1` in `_tty_info()` is `/dev/ttysXXX`

Which comes from `#{pane_tty}`
```
$ tmux display -p '#{pane_tty}'
/dev/ttys010
```

But you can give `#{s,/dev/,,:pane_tty}` a try
```
$ tmux display -p '#{s,/dev/,,:pane_tty}'
ttys010
```

I may consider applying it in `master` as the substitution feature landed in tmux 2.2 but I would like to understand what's going on first.

> So I suppose it is not because Oh My Zsh

Worth a try.

**Comment by programus** [comment] 2021-07-13 06:41
> I may consider applying it in master as the substitution feature landed in tmux 2.2 but I would like to understand what's going on first.

Yes. I agree. I think fixing this now is not so difficult, but I want to know what's going on too.

**Comment by gpakosz** [comment] 2021-07-13 07:38
Maybe https://objective-see.com/products/knockknock.html can help you figure out what's installed and my cause problems

**Comment by programus** [comment] 2021-07-13 12:20
> But you can give `#{s,/dev/,,:pane_tty}` a try
> 
> ```
> $ tmux display -p '#{s,/dev/,,:pane_tty}'
> ttys010
> ```

I just replaced all `#{pane_tty}` to `#{s,/dev/,,:pane_tty}` and it works good!

**Comment by gpakosz** [comment] 2021-07-13 12:30
> I just replaced all `#{pane_tty}` to `#{s,/dev/,,:pane_tty}` in `.tmux.conf` and it works good now. 

I might pick that solution. Still you're not the only one reporting slowness while not updating anything. Something must have changed 🙂 It's all about finding the common denominator now

**Comment by gpakosz** [comment] 2021-07-13 12:37
Also. I would triple check disabling Oh My Zsh. To make sure

**Comment by gpakosz** [comment] 2021-07-13 12:44
Look also into Bash's `$PROMPT_COMMAND` and Zsh's `preexec()`

**Comment by gpakosz** [comment] 2021-07-13 12:50
Or maybe the `DEBUG` trap is set and you can clear it with
```
$ trap - DEBUG
```

Or maybe you have `$PS0` being defined (requires Bash >= 4.4)

**Comment by gpakosz** [comment] 2021-07-14 18:31
@programus were you able to make more tests by chance?

**Comment by programus** [comment] 2021-07-16 12:49
> @programus were you able to make more tests by chance?

Sorry for late. What test do you want me to do?

**Comment by gpakosz** [comment] 2021-07-16 12:54
> What test do you want me to do?

I was curious whether you had `$PS0` defined and if you could disable the `DEBUG` trap with `trap - DEBUG` before trying the `ps` test again.

Also can you please see if you have installed apps that also appear in this list? https://github.com/gpakosz/.tmux/issues/492#issuecomment-879888773

**Comment by programus** [comment] 2021-07-16 13:35
> > What test do you want me to do?
> 
> I was curious whether you had `$PS0` defined and if you could disable the `DEBUG` trap with `trap - DEBUG` before trying the `ps` test again.
> 

No. I don't have `$PS0` defined. 

```
$ echo $PS0

```

And `trap - DEBUG` does not help at all. 

```
$ trap - DEBUG

$ date && ps -t ttys011 && date
Fri Jul 16 22:24:44 JST 2021
  PID TTY           TIME CMD
85381 ttys011    0:00.35 -zsh
Fri Jul 16 22:24:44 JST 2021

$ date && ps -t /dev/ttys011 && date
Fri Jul 16 22:24:54 JST 2021
  PID TTY           TIME CMD
85381 ttys011    0:00.35 -zsh
Fri Jul 16 22:25:37 JST 2021

```

> Also can you please see if you have installed apps that also appear in this list? [#492 (comment)](https://github.com/gpakosz/.tmux/issues/492#issuecomment-879888773)

About the installed apps, yes, there are many apps also installed on my PC. 
Seems both @maxi8815 and I are from IBM since we both have `Mac@IBM App` installed. 

Here are the apps I am sure I have in the list: 
Safari.app
Mac@IBM App
Mac@IBM Enrollment.app
Karabiner-EventViewer.app
Karabiner-Elements.app
VirtualBox.app
zoom.us.app
Mac@IBM Notifications.app
Falcon.app
Microsoft Teams.app
The Unarchiver.app
iTerm.app
Amphetamine.app
MotionPro.app
Slack.app
Code42.app
Microsoft Excel.app
Google Chrome.app
Itsycal.app
Firefox.app
Cisco Webex
Microsoft OneNote.app
Microsoft Outlook.app
Microsoft PowerPoint.app
Microsoft Word.app

I consider VIrtual Box as a suspect since I recently installed it because I want to use minikube and use it as the virtual machine. Before that I didn't have this problem. Also, I think it changes the network adapter or some system stuffs. 

I will try to uninstall it and try again.

**Comment by programus** [comment] 2021-07-16 13:48
@gpakosz OK. I uninstalled virtual box and restarted my PC, but nothing changed when I run `ps -t /dev/ttys008` . :-( 

Virtual Box may be innocent.

**Comment by gpakosz** [comment] 2021-07-16 14:03
Can you disable `Falcon.app` by chance? Random guess, Google tells me it's an anti virus + anti intrusion thing. Maybe it's inspecting commands causing the delay?

**Comment by programus** [comment] 2021-07-16 16:48
@gpakosz No, I am afraid I can't. I tried to stop Falcon and Falcon Notification from Activity Monitor, but there is always a Falcon Notification there. It would be restarted automatically once I killed one. 

I guess there were a kind of system policy from my company that keep Falcon running.

**Comment by gpakosz** [comment] 2021-07-16 19:04
Oh too bad you can't disable it.

Can your IT dept be bother doing "the `ps` test" before and after installing Falcon.app by chance?

**Comment by programus** [comment] 2021-07-20 03:32
> Oh too bad you can't disable it.
> 
> Can your IT dept be bother doing "the `ps` test" before and after installing Falcon.app by chance?

I don't think so since this actually does not affect the normal operation. :-(

**Comment by gpakosz** [comment] 2021-07-23 06:53
> I don't think so since this actually does not affect the normal operation

Well that's not how I would describe the situation given passing `/dev/xxx` to any shell script or command adds a 30s+ lag 😅

**Comment by programus** [comment] 2021-07-28 08:40
> > I don't think so since this actually does not affect the normal operation
> 
> Well that's not how I would describe the situation given passing `/dev/xxx` to any shell script or command adds a 30s+ lag 😅

Actually, not any shell script or command. I tried `ls` just now, there is no delay. I think the trigger of the problem is still not very clear.

**Comment by afafara** [comment] 2021-09-23 08:25
I can confirm the issue happening to me and with Falcon agent running on MacOS. While this is a corporate laptop and so Falcon Agent cannot be uninstalled, and on stopping it just restarts, running this command in separate shell session confirms it's what's causing the issue:
`while true; do kill -9 $(ps ax | grep falcon.Agent | grep -v grep | awk '{ print $1 }'); done`
Updating `.tmux.conf` from `'#{pane_tty}'` to `'#{s,/dev/,,:pane_tty}'` fixed it for me

**Comment by gpakosz** [comment] 2021-09-23 09:03
Heu @afafara 👋

Thanks for stepping in. Can you please confirm we're talking about Falcon from Crowdstrike? And that `$ date && ps -t /dev/ttys001 && date` takes around `30` seconds for you instead of being instant?

**Comment by afafara** [comment] 2021-09-23 09:05
@gpakosz yes exactly - it's Crowdstrike Falcon, and `date && ps -t /dev/ttys001 && date` takes up to a minute with it running, and instant with the `kill` in `while true` loop (or with workaround applied)

**Comment by gpakosz** [comment] 2021-09-24 07:24
I tried to reach out to Crowdstrike's engineering on Twitter as I'm not a customer of Falcon myself.

They told I should tell you all to reach out to support if you want them to troubleshoot the issue.

In the meantime, I pushed the `gh-492-499` branch that does the `'#{s,/dev/,,:pane_tty}'` replacement.

**Comment by gpakosz** [comment] 2021-10-03 07:44
Duplicate of #492

**Closed by gpakosz** 2021-10-03 07:44 UTC
Labels: duplicate, external
