### ISSUE TITLE
Scrollback buffer empty after ^L

### ISSUE THREAD

**Issue by unixn3rd** [gpakosz/.tmux#398] opened 2020-09-10 19:07 UTC
Hello,

I noticed that when I use [Ctrl]+L to clear my terminal screen my scrollback buffer within Oh My Tmux is empty. However when using the 'clear' command to accomplish this the scrollback buffer still contains content.

Initially I thought that perhaps this had something to do with my configuration changes. But the same problem occurs with a default configuration. I also thought that perhaps it the problem had something to do was my shell environment Zsh. But the problem persists in Bash as well. I've tested this on multiple machines.

Is this by design? Or is this a problem with Oh My Tmux?

Love your work on this project! Thank you so much for providing this to the community!

I look forward to your response.

Let me know if you need any additional information from me. Happy to assist if needed.

Thanks!
--unixn3rd

**Comment by gpakosz** [comment] 2020-09-10 19:13
Hello @unixn3rd 👋

It's by design. I don't believe it's a problem 😅
```
$ tmux list-keys | grep clear-history
bind-key    -T root         C-l                  send-keys C-l \; run-shell "sleep 0.1" \; clear-history
```

If you don't like this behavior, edit your`~/.tmux.conf.local` copy and add
```
unbind -n C-l
```

Hope that helps!

**Comment by unixn3rd** [comment] 2020-09-10 19:24
Hello @gpakosz,

Looks like I should have reviewed the config files a bit closer.

Anyhow. Thank you very much for the assistance!
--unixn3rd

**Comment by gpakosz** [comment] 2020-09-10 19:28
No problem.

I let you close the issue if you believe we're done.

**Closed** 2020-09-10 19:29 UTC
Labels: solution available, support

**Comment by snsnsjsn** [comment] 2022-06-25 06:52
I have the same requirement , and thanks for your solution.

![image](https://user-images.githubusercontent.com/11435527/175762201-b25d40c5-ff62-4b73-a94f-aa079a2cf506.png)
