### ISSUE TITLE
this is actually a request for enhancement - changing the default directory to ~/.config/

### ISSUE THREAD

**Issue by charlie39** [gpakosz/.tmux#574] opened 2022-06-12 13:44 UTC
It would be nice if the dotfiles are moved under ```~/.config``` in compliance with
XDG directory spec (```$XDG_CONFIG_HOME```).
Tmux does look for ```$XDG_CONFIG_HOME/tmux/tmux.conf``` (or ```~/.config/tmux/tmux.conf```) for user configuration file.

I have this setup and i would be glad to open a PR for it

**Comment by gpakosz** [comment] 2022-06-19 09:50
Hello @charlie39 👋

For now I don't know what's the best way to support this as Oh my tmux! also needs to locate `.tmux.conf.local`.

Duplicate of #439

**Closed by gpakosz** 2022-06-19 09:50 UTC
Labels: duplicate
