### ISSUE TITLE
Error in source file, 'cut -c3-....' and found the solution.

### ISSUE THREAD

**Issue by JackLee404** [gpakosz/.tmux#595] opened 2022-08-20 01:07 UTC
System: Ubuntu 18.04 LTS (Bionic Beaver)(on the Windows Subsystem for Linux)
tmux-version: **tmux3.4**

When I running the command `tmux source-file .tmux.conf`, it doesn't work and give me a tip:
`cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 2`

The reason may be there and I just change 'sh' to 'bash' command to run.
[bash-bad-substitution](https://stackoverflow.com/questions/20615217/bash-bad-substitution)

***
Reference from the anwser of [Vanni Totaro](https://stackoverflow.com/users/366332/vanni-totaro)

The default shell (/bin/sh) under Ubuntu points to dash, not bash.
``` bash
me@pc:~$ readlink -f $(which sh)
/bin/dash
``` 
So if you `chmod +x` your_script_file.sh and then run it with `./your_script_file.sh`, or if you run it with bash your_script_file.sh, it should work fine.

Running it with `sh your_script_file.sh` will not work because the hashbang line will be ignored and the script will be interpreted by dash, which does not support that string substitution syntax.
***

Finally, I think change `sh` to `bash` is the best solution for some weird bugs.

**Comment by gpakosz** [comment] 2022-08-20 07:17
Hello @JackLee404 👋

Please try the latest commit in the `master` branch

**Comment by gpakosz** [comment] 2022-08-21 11:26
Hello @JackLee404 👋

Were you able to try the lastest commit in the `master` branch?

**Comment by JackLee404** [comment] 2022-08-22 01:53
> Hello @JackLee404 👋
> 
> Were you able to try the lastest commit in the `master` branch?


The bug had been fixed after source-file the latest commit!

Respect to you!

**Comment by gpakosz** [comment] 2022-08-22 05:37
Duplicate of #593

**Closed by gpakosz** 2022-08-22 05:37 UTC
Labels: waiting for feedback
