### ISSUE TITLE
The colors changed after entered tmux

### ISSUE THREAD

**Issue by yyy624297803** [gpakosz/.tmux#516] opened 2021-09-16 01:03 UTC
I am a new tmux user who is glad to user oh-my-tmux. But at the same time, I am using p10k theme and vim theme. The all colors changed after I entered tmux, I want get my default colors back, what shold I do in config file?
Besides, I want to move the status bar below to the top, I don’t know if it can be configured in the configuration file.

**Comment by gpakosz** [comment] 2021-09-16 06:51
Hello @yyy624297803 👋

What's the p10k theme?

> The all colors changed after I entered tmux, I want get my default colors back, what shold I do in config file?

What colors are you talking about? Oh my tmux! doesn't alter terminal emulator colors nor vim colors. Make sure `TERM` is set to `xterm-256color` outside of tmux and remains `screen-256color` inside of tmux.

> I want to move the status bar below to the top

If you look into your `~/.tmux.conf.local` copy, you will see
```
# move status line to top
#set -g status-position top
```
Uncomment the `set -g status-position top` line

**Comment by zourdycodes** [comment] 2021-09-16 14:36
sup dude, I just want to help to fix your problem 💯  

so it's basically simple if you are using Linux (any kind of distros doesn't really matter at all) go to your `~/.profile` and `~/.bashrc` or `~/.zshrc` (only if you happen to be using zsh) and put this piece of statement at the end of the line `export TERM=xterm-256color` and `export EDITOR=vim` and don't forget to save and write this `source ~/.zshrc && source ~/.profile` afterwards. last but not least make sure that inside your `~/.tmux.conf` written this `set -g default-terminal "screen-256color"` 

tell me if you had confusion or trouble. I'll do my best. cheers 🍻

**Comment by zourdycodes** [comment] 2021-09-16 14:38
the problem is caused by rendering colour scheme that does not synchronize between vim, terminal `colour` and tmux

**Comment by yyy624297803** [comment] 2021-09-19 08:33
> Hello @yyy624297803 
> 
> What's the p10k theme?
> 
> > The all colors changed after I entered tmux, I want get my default colors back, what shold I do in config file?
> 
> What colors are you talking about? Oh my tmux! doesn't alter terminal emulator colors nor vim colors. Make sure `TERM` is set to `xterm-256color` outside of tmux and remains `screen-256color` inside of tmux.
> 
> > I want to move the status bar below to the top
> 
> If you look into your `~/.tmux.conf.local` copy, you will see
> 
> ```
> # move status line to top
> #set -g status-position top
> ```
> 
> Uncomment the `set -g status-position top` line

Thanks! But the color problem still bothers me...

**Comment by yyy624297803** [comment] 2021-09-19 08:40
> sup dude, I just want to help to fix your problem 
> 
> so it's basically simple if you are using Linux (any kind of distros doesn't really matter at all) go to your `~/.profile` and `~/.bashrc` or `~/.zshrc` (only if you happen to be using zsh) and put this piece of statement at the end of the line `export TERM=xterm-256color` and `export EDITOR=vim` and don't forget to save and write this `source ~/.zshrc && source ~/.profile` afterwards. last but not least make sure that inside your `~/.tmux.conf` written this `set -g default-terminal "screen-256color"`
> 
> tell me if you had confusion or trouble. I'll do my best. cheers

Thanks for your answer, but my problem still exits after I followed your instructions:
![Screenshot from 2021-09-19 16-36-18](https://user-images.githubusercontent.com/51949655/133920990-feb02d5c-0c6f-473d-9926-1d8044d2e056.png)
This is my normal vim color without tmux.
After I open file in tmux with vim:
![Screenshot from 2021-09-19 16-39-28](https://user-images.githubusercontent.com/51949655/133921060-abe372ae-8324-40d9-aff9-815024936993.png)
I would not appreciate it if you can help me solve this problem.

**Comment by zourdycodes** [comment] 2021-09-19 13:09
have you sourced them afterwards? if you do that's great and have you been checked the ~/.tmux.conf and written like this one `set -g default-terminal "screen-256color"`? 

if all of that step is didn't work out, I guess some config colour inside tmux/vim configuration file overwritten one and another or perhaps it is a conflict between them because, to be honest I thought your vim is changed to black n  white after opening files with tmux because similar problem happens to me a year ago.

**Comment by zourdycodes** [comment] 2021-09-19 13:11
check out this link for further solving the problem, might be helping

https://unix.stackexchange.com/questions/1045/getting-256-colors-to-work-in-tmux

https://github.com/tmux/tmux/issues/2044

**Comment by yyy624297803** [comment] 2021-09-22 10:54
> have you sourced them afterwards? if you do that's great and have you been checked the ~/.tmux.conf and written like this one `set -g default-terminal "screen-256color"`?
> 
> if all of that step is didn't work out, I guess some config colour inside tmux/vim configuration file overwritten one and another or perhaps it is a conflict between them because, to be honest I thought your vim is changed to black n white after opening files with tmux because similar problem happens to me a year ago.

I have sourced them, and I put `set -g default-terminal "screen-256color"` in `.tmux.conf`.
Thank you for your detailed answers！！！

**Comment by gpakosz** [comment] 2021-09-22 11:53
> I put `set -g default-terminal "screen-256color"` in `.tmux.conf`

Oh my tmux!'s `.tmux.conf` already contains `set -g default-terminal "screen-256color"` 🤷‍♂️
Please follow the recommendations and do not edit it.

> Although this problem can't be solved
Please try to solve it without Oh my tmux!, as this configuration doesn't alter colors in any meaningful way.
Reach out to tmux support using the mailing list or the irc channel on the libera network.

**Comment by zourdycodes** [comment] 2021-09-22 15:58
> > I put `set -g default-terminal "screen-256color"` in `.tmux.conf`
> 
> Oh my tmux!'s `.tmux.conf` already contains `set -g default-terminal "screen-256color"` 🤷‍♂️
> Please follow the recommendations and do not edit it.
> 
> > Although this problem can't be solved
> 
> Please try to solve it without Oh my tmux!, as this configuration doesn't alter colors in any meaningful way.
> Reach out to tmux support using the mailing list or the irc channel on the libera network.

dude, I think there is nothing wrong with `oh-my-tmux` the main problem is his configuration terminal colour itself that could be overwritten or conflicted. I am a Linux user too but nothing is wrong with my vim and tmux interfaces

**Comment by gpakosz** [comment] 2021-09-22 17:07
I think it's best to move the conversation to tmux support channels where it will have more visibility. Closing.

**Closed by gpakosz** 2021-09-22 17:07 UTC
Labels: tmux support, support

**Comment by cpin-fortinet** [comment] 2021-11-01 19:09
Had the same colour change issue for a long time, not a biggie but finally decided to give it a check. 
Came across this issue and confirmed my setting of `TERM` is correct.

What works for me is reverting the setting of `tmux_conf_theme_highlight_focused_pane` from `true` back to `false` (default)

```
# highlight focused pane (tmux >= 2.1), possible values are:
#   - true
#   - false (default)
tmux_conf_theme_highlight_focused_pane=false
```

When `tmux_conf_theme_highlight_focused_pane` was `true`, starting tmux will make the whole terminal theme a little bit darker in my settings.

@yuyouyu32 
I would suggest you to try the default tmux conf setting without `Oh my tmux` and see if the colour change problem is really caused by `Oh my tmux` first
