### ISSUE TITLE
how to use tmux as default shell

### ISSUE THREAD

**Issue by 0xMrR0b0t** [gpakosz/.tmux#614] opened 2022-11-10 16:55 UTC

**Comment by gpakosz** [comment] 2022-12-28 18:35
Hello @0xMrR0b0t 👋

I don't use `tmux` as the default shell myself. Please ask on the usual `tmux` support channels 😊

**Comment by gpakosz** [comment] 2022-12-28 22:48
Dupe of #587

**Comment by HXRCyberLabs** [comment] 2022-12-30 18:23
@gpakosz, Can i get only the "Copy to OS clipboard" part of the tmux.conf file, I like to keep things in default style.

**Closed** 2023-04-02 07:51 UTC
Labels: duplicate
